version: 2.1
jobs:
  build_for_test:
    docker:
      - image: circleci/node:12.16.1
    steps:
      - checkout
      - run:
          name: Update npm to v6.14.4
          command: sudo npm install -g npm@6.14.4
      - run:
          name: npm audit
          command: npm audit --production --audit-level=moderate
      - persist_to_workspace:
          root: ./
          paths:
            - '*'
      - restore_cache:
          key: v1-npm-{{ checksum "package.json" }}-{{checksum "package-lock.json" }}
      - run:
          name: Install npm dependencies
          command: '[ ! -d node_modules ] && npm ci --loglevel warn --yes || echo package.json and package-lock.json unchanged. Using cache.'
      - save_cache:
          key: v1-npm-{{ checksum "package.json" }}-{{checksum "package-lock.json" }}
          paths:
            - ./node_modules
  test:
    docker:
      - image: circleci/node:12.16.1
    steps:
      - attach_workspace:
          at: ./
      - restore_cache:
          key: v1-npm-{{ checksum "package.json" }}-{{checksum "package-lock.json" }}
      - run:
          name: Run tests and code coverage
          command: npx --no-install jest --ci --runInBand --bail --silent --coverage --projects jest.config.js jest.config.jsdom.js
  lint:
    docker:
      - image: circleci/node:12.16.1
    steps:
      - attach_workspace:
          at: ./
      - restore_cache:
          key: v1-npm-{{ checksum "package.json" }}-{{checksum "package-lock.json" }}
      - run:
          name: Lint codebase
          command: npx --no-install eslint .
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build_for_test
      - test:
          requires:
            - build_for_test
#       - lint:
#           requires:
#             - build_for_test
